INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETED)
VALUES (10001, 'EngineerSk', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETED)
VALUES (10501, 'EngineerSk', 'Get CISCO Cybersecurity Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETED)
VALUES (2053, 'EngineerSk', 'Get Kubernetes Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETED)
VALUES (1071, 'EngineerSk', 'Get Docker Certified', CURRENT_DATE(), false);